version: '3.3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - db
    placholder:
        image: alpine:latest
    db:
        image: saptarshikar/pymongo